# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ......templates.types.versioned_snippet_template import VersionedSnippetTemplate


class EndpointSnippetTemplates(UniversalBaseModel):
    typescript: typing.Optional[VersionedSnippetTemplate] = None
    python: typing.Optional[VersionedSnippetTemplate] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...type.types.list_type import ListType  # noqa: E402, F401, I001
from ...type.types.map_type import MapType  # noqa: E402, F401, I001
from ...type.types.nullable_type import NullableType  # noqa: E402, F401, I001
from ...type.types.optional_type import OptionalType  # noqa: E402, F401, I001
from ...type.types.set_type import SetType  # noqa: E402, F401, I001
from ......templates.types.dict_template import DictTemplate  # noqa: E402, F401, I001
from ......templates.types.discriminated_union_template import DiscriminatedUnionTemplate  # noqa: E402, F401, I001
from ......templates.types.generic_template import GenericTemplate  # noqa: E402, F401, I001
from ......templates.types.iterable_template import IterableTemplate  # noqa: E402, F401, I001
from ......templates.types.union_template import UnionTemplate  # noqa: E402, F401, I001
from ......templates.types.union_template_member import UnionTemplateMember  # noqa: E402, F401, I001
from ......templates.types.union_template_v_2 import UnionTemplateV2  # noqa: E402, F401, I001

update_forward_refs(EndpointSnippetTemplates)
