# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ......core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ......core.serialization import FieldMetadata
from ....commons.types.with_description import WithDescription
from .http_response_body_shape import HttpResponseBodyShape


class HttpResponse(WithDescription):
    type: HttpResponseBodyShape
    status_code: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="statusCode")] = pydantic.Field(
        default=None
    )
    """
    Defaults to 200
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...type.types.list_type import ListType  # noqa: E402, F401, I001
from ...type.types.map_type import MapType  # noqa: E402, F401, I001
from ...type.types.nullable_type import NullableType  # noqa: E402, F401, I001
from ...type.types.optional_type import OptionalType  # noqa: E402, F401, I001
from ...type.types.set_type import SetType  # noqa: E402, F401, I001

update_forward_refs(HttpResponse)
