# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ......core.pydantic_utilities import IS_PYDANTIC_V2
from ......core.serialization import FieldMetadata
from ....commons.types.with_description import WithDescription
from .http_response_body_shape import HttpResponseBodyShape


class HttpResponse(WithDescription):
    type: HttpResponseBodyShape
    status_code: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="statusCode")] = pydantic.Field(
        default=None
    )
    """
    Defaults to 200
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
