# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ......core.serialization import FieldMetadata
from .non_stream_response import NonStreamResponse
from .stream_condition import StreamCondition
from .stream_response import StreamResponse


class StreamConditionResponse(UniversalBaseModel):
    response: NonStreamResponse
    stream_response: typing_extensions.Annotated[StreamResponse, FieldMetadata(alias="streamResponse")]
    stream_condition: typing_extensions.Annotated[StreamCondition, FieldMetadata(alias="streamCondition")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...type.types.list_type import ListType  # noqa: E402, F401, I001
from ...type.types.map_type import MapType  # noqa: E402, F401, I001
from ...type.types.nullable_type import NullableType  # noqa: E402, F401, I001
from ...type.types.optional_type import OptionalType  # noqa: E402, F401, I001
from ...type.types.set_type import SetType  # noqa: E402, F401, I001

update_forward_refs(StreamConditionResponse)
