# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from .playground_settings import PlaygroundSettings
from .with_api_definition_id import WithApiDefinitionId
from .with_node_metadata import WithNodeMetadata
from .with_overview_page import WithOverviewPage
from .with_redirect import WithRedirect


class ApiPackageNode(WithNodeMetadata, WithOverviewPage, WithApiDefinitionId, WithRedirect):
    type: typing.Literal["apiPackage"] = "apiPackage"
    children: typing.List["ApiPackageChild"]
    playground: typing.Optional[PlaygroundSettings] = pydantic.Field(default=None)
    """
    Settings for the api playground that is applied only to descendants of this api package.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .api_package_child import ApiPackageChild  # noqa: E402, F401, I001

update_forward_refs(ApiPackageNode)
