# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .endpoint_node import EndpointNode
from .endpoint_pair_node import EndpointPairNode
from .grpc_node import GrpcNode
from .link_node import LinkNode
from .page_node import PageNode
from .web_socket_node import WebSocketNode
from .webhook_node import WebhookNode

if typing.TYPE_CHECKING:
    from .api_package_node import ApiPackageNode
ApiPackageChild = typing.Union[
    "ApiPackageNode", EndpointNode, EndpointPairNode, WebSocketNode, WebhookNode, GrpcNode, PageNode, LinkNode
]
