# This file was auto-generated by Fern from our API Definition.

import typing

NavigationV1Availability = typing.Union[
    typing.Literal["stable", "generally-available", "in-development", "pre-release", "beta", "deprecated"], typing.Any
]
