# This file was auto-generated by Fern from our API Definition.

import typing

from .api_reference_node import ApiReferenceNode
from .section_node import SectionNode
from .sidebar_group_node import SidebarGroupNode

SidebarRootChild = typing.Union[SidebarGroupNode, ApiReferenceNode, SectionNode]
