# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....commons.types.http_method import HttpMethod
from ....commons.types.webhook_id import WebhookId
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from .with_api_definition_id import WithApiDefinitionId
from .with_node_metadata import WithNodeMetadata


class WebhookNode(WithNodeMetadata, WithApiDefinitionId):
    type: typing.Literal["webhook"] = "webhook"
    method: HttpMethod
    webhook_id: typing_extensions.Annotated[WebhookId, FieldMetadata(alias="webhookId")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
