# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...snippets.types.go_sdk import GoSdk
from .single_go_snippet_create import SingleGoSnippetCreate


class GoSdkSnippetsCreate(UniversalBaseModel):
    sdk: GoSdk
    snippets: typing.List[SingleGoSnippetCreate]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
