# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from .base_snippet_create import BaseSnippetCreate
from .csharp_snippet_code import CsharpSnippetCode


class SingleCsharpSnippetCreate(BaseSnippetCreate):
    snippet: CsharpSnippetCode

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
