# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .....core.serialization import FieldMetadata


class PrivateAuthConfig(UniversalBaseModel):
    """
    Use SSO to authenticate users before they can access the docs.
    """

    auth_type: typing_extensions.Annotated[typing.Literal["sso"], FieldMetadata(alias="authType")] = "sso"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
