# This file was auto-generated by Fern from our API Definition.

import typing

from ...commons.types.file_id_or_url import FileIdOrUrl
from .logo_configuration import LogoConfiguration

Logo = typing.Union[FileIdOrUrl, LogoConfiguration]
