# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .changelog_entry import ChangelogEntry
from .yank import Yank


class ReleaseRequest(UniversalBaseModel):
    version: str
    created_at: typing_extensions.Annotated[typing.Optional[dt.date], FieldMetadata(alias="createdAt")] = None
    is_yanked: typing_extensions.Annotated[typing.Optional[Yank], FieldMetadata(alias="isYanked")] = None
    changelog_entry: typing_extensions.Annotated[
        typing.Optional[typing.List[ChangelogEntry]], FieldMetadata(alias="changelogEntry")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
