# This file was auto-generated by Fern from our API Definition.

from ....v_1.read.endpoint.types.language import Language as api_v_1_read_endpoint_types_language_Language

Language = api_v_1_read_endpoint_types_language_Language
