# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from .....commons.types.page_id import PageId
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .....core.serialization import FieldMetadata
from .docs_config import DocsConfig
from .page_content import PageContent


class DocsDefinition(UniversalBaseModel):
    pages: typing.Dict[PageId, PageContent]
    config: DocsConfig
    js_files: typing_extensions.Annotated[typing.Optional[typing.Dict[str, str]], FieldMetadata(alias="jsFiles")] = (
        pydantic.Field(default=None)
    )
    """
    A map of file names to their contents. 
    The key is the absolute path file name and the value is the file contents.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
