# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from .....commons.types.page_id import PageId
from .....core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from .....core.serialization import FieldMetadata
from .navigation_node_metadata import NavigationNodeMetadata


class DocsSection(NavigationNodeMetadata):
    title: str
    items: typing.List["NavigationItem"]
    collapsed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    This is only applicable to sections that are at the root level in the sidebar.
    If false, the section title will be displayed as a header and the items will be displayed below it, and cannot be collapsed.
    """

    skip_url_slug: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="skipUrlSlug")] = None
    overview_page_id: typing_extensions.Annotated[typing.Optional[PageId], FieldMetadata(alias="overviewPageId")] = (
        pydantic.Field(default=None)
    )
    """
    If provided, clicking on this section will open this page instead of the first page in the section.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .api_navigation_config_subpackage import ApiNavigationConfigSubpackage  # noqa: E402, F401, I001
from .....navigation.v_1.types.api_package_node import ApiPackageNode  # noqa: E402, F401, I001
from .navigation_item import NavigationItem  # noqa: E402, F401, I001

update_forward_refs(DocsSection)
