# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, UniversalRootModel, update_forward_refs

T_Result = typing.TypeVar("T_Result")


class _Factory:
    def base_64(self, value: str) -> BytesValue:
        if IS_PYDANTIC_V2:
            return BytesValue(root=_BytesValue.Base64(type="base64", value=value))  # type: ignore
        else:
            return BytesValue(__root__=_BytesValue.Base64(type="base64", value=value))  # type: ignore


class BytesValue(UniversalRootModel):
    factory: typing.ClassVar[_Factory] = _Factory()

    if IS_PYDANTIC_V2:
        root: typing.Union[_BytesValue.Base64]

        def get_as_union(self) -> typing.Union[_BytesValue.Base64]:
            return self.root
    else:
        __root__: typing.Union[_BytesValue.Base64]

        def get_as_union(self) -> typing.Union[_BytesValue.Base64]:
            return self.__root__

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        if IS_PYDANTIC_V2:
            return self.root.dict(**kwargs)
        else:
            return self.__root__.dict(**kwargs)

    def visit(self, base_64: typing.Callable[[str], T_Result]) -> T_Result:
        unioned_value = self.get_as_union()
        if unioned_value.type == "base64":
            return base_64(unioned_value.value)

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True


class _BytesValue:
    class Base64(UniversalBaseModel):
        type: typing.Literal["base64"] = "base64"
        value: str

        if IS_PYDANTIC_V2:
            model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
        else:

            class Config:
                frozen = True
                smart_union = True


update_forward_refs(BytesValue)
