# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.api_error import ApiError
from ..types.pull_request_not_found import PullRequestNotFound


class PullRequestNotFoundError(ApiError):
    def __init__(self, body: PullRequestNotFound, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=404, headers=headers, body=body)
