# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....commons.types.endpoint_id import EndpointId
from ....commons.types.http_method import HttpMethod
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from .playground_settings import PlaygroundSettings
from .with_api_definition_id import WithApiDefinitionId
from .with_node_metadata import WithNodeMetadata


class EndpointNode(WithNodeMetadata, WithApiDefinitionId):
    type: typing.Literal["endpoint"] = "endpoint"
    method: HttpMethod
    endpoint_id: typing_extensions.Annotated[EndpointId, FieldMetadata(alias="endpointId")]
    is_response_stream: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isResponseStream")] = (
        None
    )
    playground: typing.Optional[PlaygroundSettings] = pydantic.Field(default=None)
    """
    Settings for the api playground that affect this endpoint specifically.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
