# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ....core.serialization import FieldMetadata
from .landing_page_node import LandingPageNode
from .product_node import ProductNode
from .with_node_id import WithNodeId


class ProductGroupNode(WithNodeId):
    type: typing.Literal["productgroup"] = "productgroup"
    landing_page: typing_extensions.Annotated[typing.Optional[LandingPageNode], FieldMetadata(alias="landingPage")] = (
        None
    )
    children: typing.List[ProductNode] = pydantic.Field()
    """
    The individual products being documented
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .api_package_node import ApiPackageNode  # noqa: E402, F401, I001
from .section_node import SectionNode  # noqa: E402, F401, I001

update_forward_refs(ProductGroupNode)
