# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from .with_node_metadata import WithNodeMetadata
from .with_overview_page import WithOverviewPage
from .with_redirect import WithRedirect


class SectionNode(WithNodeMetadata, WithOverviewPage, WithRedirect):
    type: typing.Literal["section"] = "section"
    collapsed: typing.Optional[bool] = None
    children: typing.List["NavigationChild"]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .navigation_child import NavigationChild  # noqa: E402, F401, I001

update_forward_refs(SectionNode)
