# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from .sidebar_root_child import SidebarRootChild
from .with_node_id import WithNodeId


class SidebarRootNode(WithNodeId):
    type: typing.Literal["sidebarRoot"] = "sidebarRoot"
    children: typing.List[SidebarRootChild]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .api_package_node import ApiPackageNode  # noqa: E402, F401, I001
from .section_node import SectionNode  # noqa: E402, F401, I001

update_forward_refs(SidebarRootNode)
