# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ......commons.types.endpoint_id import EndpointId
from ......commons.types.environment_id import EnvironmentId
from ......commons.types.http_method import HttpMethod
from ......core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ......core.serialization import FieldMetadata
from ....commons.types.environment import Environment
from ....commons.types.protocol import Protocol
from ....commons.types.with_availability import WithAvailability
from ....commons.types.with_description import WithDescription
from ....read.endpoint.types.endpoint_path import EndpointPath
from ....read.endpoint.types.endpoint_snippet_templates import EndpointSnippetTemplates
from ....read.endpoint.types.error_declaration import ErrorDeclaration
from ....read.endpoint.types.error_declaration_v_2 import ErrorDeclarationV2
from ....read.endpoint.types.example_endpoint_call import ExampleEndpointCall
from ....read.endpoint.types.header import Header
from ....read.endpoint.types.http_response import HttpResponse
from ....read.endpoint.types.http_responses_v_2 import HttpResponsesV2
from ....read.endpoint.types.query_parameter import QueryParameter
from .db_http_request import DbHttpRequest
from .db_http_requests_v_2 import DbHttpRequestsV2


class DbEndpointDefinition(WithDescription, WithAvailability):
    authed: typing.Optional[bool] = None
    default_environment: typing_extensions.Annotated[
        typing.Optional[EnvironmentId], FieldMetadata(alias="defaultEnvironment")
    ] = None
    environments: typing.Optional[typing.List[Environment]] = None
    method: HttpMethod
    id: EndpointId
    original_endpoint_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="originalEndpointId")
    ] = None
    url_slug: typing_extensions.Annotated[str, FieldMetadata(alias="urlSlug")]
    migrated_from_url_slugs: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="migratedFromUrlSlugs")
    ] = None
    name: typing.Optional[str] = None
    path: EndpointPath
    query_parameters: typing_extensions.Annotated[typing.List[QueryParameter], FieldMetadata(alias="queryParameters")]
    headers: typing.List[Header]
    request: typing.Optional[DbHttpRequest] = None
    requests_v_2: typing_extensions.Annotated[typing.Optional[DbHttpRequestsV2], FieldMetadata(alias="requestsV2")] = (
        None
    )
    response: typing.Optional[HttpResponse] = None
    responses_v_2: typing_extensions.Annotated[typing.Optional[HttpResponsesV2], FieldMetadata(alias="responsesV2")] = (
        None
    )
    errors: typing.Optional[typing.List[ErrorDeclaration]] = None
    errors_v_2: typing_extensions.Annotated[
        typing.Optional[typing.List[ErrorDeclarationV2]], FieldMetadata(alias="errorsV2")
    ] = None
    examples: typing.List[ExampleEndpointCall]
    snippet_templates: typing_extensions.Annotated[
        typing.Optional[EndpointSnippetTemplates], FieldMetadata(alias="snippetTemplates")
    ] = None
    protocol: typing.Optional[Protocol] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ....read.type.types.list_type import ListType  # noqa: E402, F401, I001
from ....read.type.types.map_type import MapType  # noqa: E402, F401, I001
from ....read.type.types.nullable_type import NullableType  # noqa: E402, F401, I001
from ....read.type.types.optional_type import OptionalType  # noqa: E402, F401, I001
from ....read.type.types.set_type import SetType  # noqa: E402, F401, I001
from ......templates.types.dict_template import DictTemplate  # noqa: E402, F401, I001
from ......templates.types.discriminated_union_template import DiscriminatedUnionTemplate  # noqa: E402, F401, I001
from ......templates.types.generic_template import GenericTemplate  # noqa: E402, F401, I001
from ......templates.types.iterable_template import IterableTemplate  # noqa: E402, F401, I001
from ......templates.types.union_template import UnionTemplate  # noqa: E402, F401, I001
from ......templates.types.union_template_member import UnionTemplateMember  # noqa: E402, F401, I001
from ......templates.types.union_template_v_2 import UnionTemplateV2  # noqa: E402, F401, I001

update_forward_refs(DbEndpointDefinition)
