# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ......core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ......core.serialization import FieldMetadata
from ....commons.types.with_description import WithDescription
from ....read.endpoint.types.http_request_body_shape import HttpRequestBodyShape


class DbHttpRequest(WithDescription):
    content_type: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="contentType")] = None
    type: HttpRequestBodyShape

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ....read.type.types.list_type import ListType  # noqa: E402, F401, I001
from ....read.type.types.map_type import MapType  # noqa: E402, F401, I001
from ....read.type.types.nullable_type import NullableType  # noqa: E402, F401, I001
from ....read.type.types.optional_type import OptionalType  # noqa: E402, F401, I001
from ....read.type.types.set_type import SetType  # noqa: E402, F401, I001

update_forward_refs(DbHttpRequest)
