# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...snippets.types.java_sdk import JavaSdk
from .single_java_snippet_create import SingleJavaSnippetCreate


class JavaSdkSnippetsCreate(UniversalBaseModel):
    sdk: JavaSdk
    snippets: typing.List[SingleJavaSnippetCreate]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
