# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...snippets.types.python_sdk import PythonSdk
from .single_python_snippet_create import SinglePythonSnippetCreate


class PythonSdkSnippetCreate(UniversalBaseModel):
    sdk: PythonSdk
    snippets: typing.List[SinglePythonSnippetCreate]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
