# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ......commons.types.type_id import TypeId
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .type_reference_id_default import TypeReferenceIdDefault


class TypeReferenceId(UniversalBaseModel):
    value: TypeId
    default: typing.Optional[TypeReferenceIdDefault] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
