# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ......commons.types.property_key import PropertyKey
from ......core.pydantic_utilities import IS_PYDANTIC_V2
from ......core.serialization import FieldMetadata
from ....commons.types.with_availability import WithAvailability
from ....commons.types.with_description import WithDescription
from .content_type import ContentType


class FilePropertyArray(WithDescription, WithAvailability):
    key: PropertyKey
    is_optional: typing_extensions.Annotated[bool, FieldMetadata(alias="isOptional")]
    content_type: typing_extensions.Annotated[typing.Optional[ContentType], FieldMetadata(alias="contentType")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
