# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ......core.pydantic_utilities import IS_PYDANTIC_V2
from ....commons.types.with_availability import WithAvailability
from ....commons.types.with_description import WithDescription
from .form_data_property import FormDataProperty


class FormDataRequest(WithDescription, WithAvailability):
    name: str
    properties: typing.List[FormDataProperty]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
