# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class LiteralType_BooleanLiteral(UniversalBaseModel):
    value: bool
    type: typing.Literal["booleanLiteral"] = "booleanLiteral"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True


class LiteralType_StringLiteral(UniversalBaseModel):
    value: str
    type: typing.Literal["stringLiteral"] = "stringLiteral"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True


LiteralType = typing.Union[LiteralType_BooleanLiteral, LiteralType_StringLiteral]
