# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from .....commons.types.api_definition_id import ApiDefinitionId
from .....commons.types.file_id import FileId
from .....commons.types.page_id import PageId
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .....core.serialization import FieldMetadata
from ...commons.commons.types.colors_config import ColorsConfig
from ...read.types.page_content import PageContent
from .db_file_info import DbFileInfo
from .docs_db_config import DocsDbConfig


class DocsDefinitionDbV1(UniversalBaseModel):
    pages: typing.Dict[PageId, PageContent]
    referenced_apis: typing_extensions.Annotated[typing.Set[ApiDefinitionId], FieldMetadata(alias="referencedApis")]
    files: typing.Dict[FileId, DbFileInfo]
    config: DocsDbConfig
    colors: typing.Optional[ColorsConfig] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
