# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from .....commons.types.type_id import TypeId
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .....core.serialization import FieldMetadata
from ...commons.types.subpackage_id import SubpackageId
from ..endpoint.types.endpoint_definition import EndpointDefinition
from ..webhook.types.webhook_definition import WebhookDefinition
from ..websocket.types.web_socket_channel import WebSocketChannel


class ApiDefinitionPackage(UniversalBaseModel):
    endpoints: typing.List[EndpointDefinition]
    websockets: typing.List[WebSocketChannel]
    webhooks: typing.List[WebhookDefinition]
    types: typing.List[TypeId]
    subpackages: typing.List[SubpackageId]
    points_to: typing_extensions.Annotated[typing.Optional[SubpackageId], FieldMetadata(alias="pointsTo")] = (
        pydantic.Field(default=None)
    )
    """
    if present, this package should be replaced with the provided subpackage
    in the docs navigation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ..type.types.list_type import ListType  # noqa: E402, F401, I001
from ..type.types.map_type import MapType  # noqa: E402, F401, I001
from ..type.types.nullable_type import NullableType  # noqa: E402, F401, I001
from ..type.types.optional_type import OptionalType  # noqa: E402, F401, I001
from ..type.types.set_type import SetType  # noqa: E402, F401, I001
from .....templates.types.dict_template import DictTemplate  # noqa: E402, F401, I001
from .....templates.types.discriminated_union_template import DiscriminatedUnionTemplate  # noqa: E402, F401, I001
from .....templates.types.generic_template import GenericTemplate  # noqa: E402, F401, I001
from .....templates.types.iterable_template import IterableTemplate  # noqa: E402, F401, I001
from .....templates.types.union_template import UnionTemplate  # noqa: E402, F401, I001
from .....templates.types.union_template_member import UnionTemplateMember  # noqa: E402, F401, I001
from .....templates.types.union_template_v_2 import UnionTemplateV2  # noqa: E402, F401, I001

update_forward_refs(ApiDefinitionPackage)
