# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ......core.serialization import FieldMetadata
from .font_config_v_2 import FontConfigV2


class DocsTypographyConfigV2(UniversalBaseModel):
    headings_font: typing_extensions.Annotated[typing.Optional[FontConfigV2], FieldMetadata(alias="headingsFont")] = (
        None
    )
    body_font: typing_extensions.Annotated[typing.Optional[FontConfigV2], FieldMetadata(alias="bodyFont")] = None
    code_font: typing_extensions.Annotated[typing.Optional[FontConfigV2], FieldMetadata(alias="codeFont")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
