# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ......commons.types.file_id import FileId
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ......core.serialization import FieldMetadata
from .js_script_strategy import JsScriptStrategy


class JsFileConfig(UniversalBaseModel):
    file_id: typing_extensions.Annotated[FileId, FieldMetadata(alias="fileId")]
    strategy: typing.Optional[JsScriptStrategy] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
