# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from .....core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from .....core.serialization import FieldMetadata
from ...commons.types.with_description import WithDescription
from .http_request_body_shape import HttpRequestBodyShape


class HttpRequest(WithDescription):
    content_type: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="contentType")] = None
    body: HttpRequestBodyShape

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...type.types.discriminated_union_type import DiscriminatedUnionType  # noqa: E402, F401, I001
from ...type.types.discriminated_union_variant import DiscriminatedUnionVariant  # noqa: E402, F401, I001
from ...type.types.list_type import ListType  # noqa: E402, F401, I001
from ...type.types.map_type import MapType  # noqa: E402, F401, I001
from ...type.types.nullable_type import NullableType  # noqa: E402, F401, I001
from ...type.types.object_property import ObjectProperty  # noqa: E402, F401, I001
from ...type.types.object_type import ObjectType  # noqa: E402, F401, I001
from ...type.types.optional_type import OptionalType  # noqa: E402, F401, I001
from ...type.types.set_type import SetType  # noqa: E402, F401, I001
from ...type.types.undiscriminated_union_type import UndiscriminatedUnionType  # noqa: E402, F401, I001
from ...type.types.undiscriminated_union_variant import UndiscriminatedUnionVariant  # noqa: E402, F401, I001

update_forward_refs(HttpRequest)
