# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from .....core.pydantic_utilities import IS_PYDANTIC_V2
from .....core.serialization import FieldMetadata
from ....v_1.write.types.start_docs_register_response import StartDocsRegisterResponse


class StartDocsPreviewRegisterResponse(StartDocsRegisterResponse):
    preview_url: typing_extensions.Annotated[str, FieldMetadata(alias="previewUrl")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
