# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .latest.client import AsyncLatestClient, LatestClient
from .raw_client import AsyncRawApiClient, RawApiClient
from .v_1.client import AsyncV1Client, V1Client


class ApiClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawApiClient(client_wrapper=client_wrapper)
        self.latest = LatestClient(client_wrapper=client_wrapper)

        self.v_1 = V1Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawApiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawApiClient
        """
        return self._raw_client


class AsyncApiClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawApiClient(client_wrapper=client_wrapper)
        self.latest = AsyncLatestClient(client_wrapper=client_wrapper)

        self.v_1 = AsyncV1Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawApiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawApiClient
        """
        return self._raw_client
