# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ....core.serialization import FieldMetadata
from .changelog_node import ChangelogNode
from .playground_settings import PlaygroundSettings
from .with_api_definition_id import WithApiDefinitionId
from .with_node_metadata import WithNodeMetadata
from .with_overview_page import WithOverviewPage
from .with_redirect import WithRedirect


class ApiReferenceNode(WithNodeMetadata, WithOverviewPage, WithApiDefinitionId, WithRedirect):
    type: typing.Literal["apiReference"] = "apiReference"
    paginated: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, long-scrolling will be disabled.
    """

    show_errors: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="showErrors")] = None
    hide_title: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="hideTitle")] = None
    children: typing.List["ApiPackageChild"]
    changelog: typing.Optional[ChangelogNode] = None
    playground: typing.Optional[PlaygroundSettings] = pydantic.Field(default=None)
    """
    Settings for the api playground that affects all endpoints.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .api_package_child import ApiPackageChild  # noqa: E402, F401, I001

update_forward_refs(ApiReferenceNode)
