# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ......core.pydantic_utilities import IS_PYDANTIC_V2
from ......core.serialization import FieldMetadata
from ....commons.types.web_socket_message_id import WebSocketMessageId
from ....commons.types.web_socket_message_origin import WebSocketMessageOrigin
from ....commons.types.with_availability import WithAvailability
from ....commons.types.with_description import WithDescription
from .web_socket_message_body_shape import WebSocketMessageBodyShape


class WebSocketMessage(WithDescription, WithAvailability):
    type: WebSocketMessageId
    display_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="displayName")] = None
    origin: WebSocketMessageOrigin
    body: WebSocketMessageBodyShape

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
