# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ...core.serialization import FieldMetadata
from .payload_input import PayloadInput


class DictTemplate(UniversalBaseModel):
    imports: typing.Optional[typing.List[str]] = None
    is_optional: typing_extensions.Annotated[bool, FieldMetadata(alias="isOptional")] = pydantic.Field()
    """
    We might not need this, but the idea here is to be able to omit if it's optional and undefined,
    or default if omitted and required.
    """

    container_template_string: typing_extensions.Annotated[str, FieldMetadata(alias="containerTemplateString")] = (
        pydantic.Field()
    )
    """
    Commonly the braces of a container like `{ $FERN_INPUT }`, but may even be something like `new Dict( $FERN_INPUT )`
    """

    delimiter: str
    key_template: typing_extensions.Annotated["Template", FieldMetadata(alias="keyTemplate")]
    value_template: typing_extensions.Annotated["Template", FieldMetadata(alias="valueTemplate")]
    key_value_separator: typing_extensions.Annotated[str, FieldMetadata(alias="keyValueSeparator")]
    template_input: typing_extensions.Annotated[typing.Optional[PayloadInput], FieldMetadata(alias="templateInput")] = (
        None
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .template import Template  # noqa: E402, F401, I001

update_forward_refs(DictTemplate)
