# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .subpackage_id import SubpackageId


class WithNamespace(UniversalBaseModel):
    namespace: typing.Optional[typing.List[SubpackageId]] = pydantic.Field(default=None)
    """
    A list of subpackage names based on the order in which values are rendered in the frontend.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
