# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from .....commons.types.api_definition_id import ApiDefinitionId
from .....commons.types.file_id import FileId
from .....commons.types.page_id import PageId
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .....core.serialization import FieldMetadata
from ...commons.commons.types.colors_config import ColorsConfig
from ...commons.commons.types.docs_typography_config import DocsTypographyConfig
from ...read.types.page_content import PageContent
from .db_file_info import DbFileInfo
from .docs_db_config import DocsDbConfig


class DocsDefinitionDbV2(UniversalBaseModel):
    pages: typing.Dict[PageId, PageContent]
    referenced_apis: typing_extensions.Annotated[typing.Set[ApiDefinitionId], FieldMetadata(alias="referencedApis")]
    files: typing.Dict[FileId, DbFileInfo]
    config: DocsDbConfig
    colors: typing.Optional[ColorsConfig] = None
    typography: typing.Optional[DocsTypographyConfig] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .docs_section import DocsSection  # noqa: E402, F401, I001
from ...read.types.api_navigation_config_subpackage import ApiNavigationConfigSubpackage  # noqa: E402, F401, I001
from .....navigation.v_1.types.api_package_node import ApiPackageNode  # noqa: E402, F401, I001
from .....navigation.v_1.types.section_node import SectionNode  # noqa: E402, F401, I001

update_forward_refs(DocsDefinitionDbV2)
