# This file was auto-generated by Fern from our API Definition.

import typing

from ..commons.types.api_definition_id import ApiDefinitionId
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawDiffClient, RawDiffClient
from .types.api_diff import ApiDiff


class DiffClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDiffClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDiffClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDiffClient
        """
        return self._raw_client

    def diff(
        self,
        *,
        previous_api_definition_id: ApiDefinitionId,
        current_api_definition_id: ApiDefinitionId,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiDiff:
        """
        Parameters
        ----------
        previous_api_definition_id : ApiDefinitionId
            The id of the previous version of the api definition

        current_api_definition_id : ApiDefinitionId
            The id of the current version of the api definition

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiDiff
            The diff between the previous and current api definitions

        Examples
        --------
        import uuid

        from fern import FernRegistry

        client = FernRegistry(
            token="YOUR_TOKEN",
        )
        client.diff.diff(
            previous_api_definition_id=uuid.UUID(
                "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            ),
            current_api_definition_id=uuid.UUID(
                "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            ),
        )
        """
        _response = self._raw_client.diff(
            previous_api_definition_id=previous_api_definition_id,
            current_api_definition_id=current_api_definition_id,
            request_options=request_options,
        )
        return _response.data


class AsyncDiffClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDiffClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDiffClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDiffClient
        """
        return self._raw_client

    async def diff(
        self,
        *,
        previous_api_definition_id: ApiDefinitionId,
        current_api_definition_id: ApiDefinitionId,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApiDiff:
        """
        Parameters
        ----------
        previous_api_definition_id : ApiDefinitionId
            The id of the previous version of the api definition

        current_api_definition_id : ApiDefinitionId
            The id of the current version of the api definition

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiDiff
            The diff between the previous and current api definitions

        Examples
        --------
        import asyncio
        import uuid

        from fern import AsyncFernRegistry

        client = AsyncFernRegistry(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.diff.diff(
                previous_api_definition_id=uuid.UUID(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
                current_api_definition_id=uuid.UUID(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.diff(
            previous_api_definition_id=previous_api_definition_id,
            current_api_definition_id=current_api_definition_id,
            request_options=request_options,
        )
        return _response.data
