# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from .....commons.types.page_id import PageId
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .....core.serialization import FieldMetadata


class ApiNavigationConfigRoot(UniversalBaseModel):
    summary_page_id: typing_extensions.Annotated[typing.Optional[PageId], FieldMetadata(alias="summaryPageId")] = None
    items: typing.List["ApiNavigationConfigItem"]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .api_navigation_config_item import ApiNavigationConfigItem  # noqa: E402, F401, I001

update_forward_refs(ApiNavigationConfigRoot)
