# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from .....commons.types.api_definition_id import ApiDefinitionId
from .....core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from .....core.serialization import FieldMetadata
from .api_artifacts import ApiArtifacts
from .api_navigation_config_root import ApiNavigationConfigRoot
from .changelog_section import ChangelogSection
from .navigation_node_metadata import NavigationNodeMetadata


class ApiSection(NavigationNodeMetadata):
    title: str
    api: ApiDefinitionId
    skip_url_slug: typing_extensions.Annotated[bool, FieldMetadata(alias="skipUrlSlug")]
    artifacts: typing.Optional[ApiArtifacts] = None
    show_errors: typing_extensions.Annotated[bool, FieldMetadata(alias="showErrors")]
    changelog: typing.Optional[ChangelogSection] = None
    navigation: typing.Optional[ApiNavigationConfigRoot] = None
    long_scrolling: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="longScrolling")] = None
    flattened: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .api_navigation_config_subpackage import ApiNavigationConfigSubpackage  # noqa: E402, F401, I001

update_forward_refs(ApiSection)
