# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from .....commons.types.page_id import PageId
from .....core.pydantic_utilities import IS_PYDANTIC_V2
from .....core.serialization import FieldMetadata
from .changelog_item import ChangelogItem
from .navigation_node_metadata import NavigationNodeMetadata


class ChangelogSection(NavigationNodeMetadata):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    page_id: typing_extensions.Annotated[typing.Optional[PageId], FieldMetadata(alias="pageId")] = None
    items: typing.List[ChangelogItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
