# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .....core.serialization import FieldMetadata
from .navigation_tab import NavigationTab
from .page_metadata import PageMetadata


class UnversionedTabbedNavigationConfig(UniversalBaseModel):
    tabs: typing.List[NavigationTab]
    landing_page: typing_extensions.Annotated[typing.Optional[PageMetadata], FieldMetadata(alias="landingPage")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
