# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .versioned_navigation_config_data import VersionedNavigationConfigData


class VersionedNavigationConfig(UniversalBaseModel):
    versions: typing.List[VersionedNavigationConfigData]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .api_navigation_config_subpackage import ApiNavigationConfigSubpackage  # noqa: E402, F401, I001
from .docs_section import DocsSection  # noqa: E402, F401, I001
from .....navigation.v_1.types.api_package_node import ApiPackageNode  # noqa: E402, F401, I001

update_forward_refs(VersionedNavigationConfig)
