# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TypeReferenceIdDefault_Enum(UniversalBaseModel):
    value: str
    type: typing.Literal["enum"] = "enum"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True


TypeReferenceIdDefault = TypeReferenceIdDefault_Enum
