# This file was auto-generated by Fern from our API Definition.

from ....v_1.read.type.types.bytes_request import BytesRequest as api_v_1_read_type_types_bytes_request_BytesRequest

BytesRequest = api_v_1_read_type_types_bytes_request_BytesRequest
