# This file was auto-generated by Fern from our API Definition.

from ....v_1.read.type.types.content_type import ContentType as api_v_1_read_type_types_content_type_ContentType

ContentType = api_v_1_read_type_types_content_type_ContentType
