# This file was auto-generated by Fern from our API Definition.

from ....v_1.read.type.types.literal_type import LiteralType as api_v_1_read_type_types_literal_type_LiteralType

LiteralType = api_v_1_read_type_types_literal_type_LiteralType
