# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ......core.serialization import FieldMetadata
from .amplitude_config import AmplitudeConfig
from .clear_bit_config import ClearBitConfig
from .fathom_config import FathomConfig
from .full_story_analytics_config import FullStoryAnalyticsConfig
from .google_analytics_4_config import GoogleAnalytics4Config
from .gtm_config import GtmConfig
from .heap_config import HeapConfig
from .hot_jar_config import HotJarConfig
from .intercom_config import IntercomConfig
from .koala_config import KoalaConfig
from .log_rocket_config import LogRocketConfig
from .mixpanel_config import MixpanelConfig
from .pirsch_config import PirschConfig
from .plausible_config import PlausibleConfig
from .post_hog_config import PostHogConfig
from .segment_config import SegmentConfig


class AnalyticsConfig(UniversalBaseModel):
    segment: typing.Optional[SegmentConfig] = None
    fullstory: typing.Optional[FullStoryAnalyticsConfig] = None
    intercom: typing.Optional[IntercomConfig] = None
    posthog: typing.Optional[PostHogConfig] = None
    gtm: typing.Optional[GtmConfig] = None
    ga_4: typing_extensions.Annotated[typing.Optional[GoogleAnalytics4Config], FieldMetadata(alias="ga4")] = None
    amplitude: typing.Optional[AmplitudeConfig] = None
    mixpanel: typing.Optional[MixpanelConfig] = None
    hotjar: typing.Optional[HotJarConfig] = None
    koala: typing.Optional[KoalaConfig] = None
    logrocket: typing.Optional[LogRocketConfig] = None
    pirsch: typing.Optional[PirschConfig] = None
    plausible: typing.Optional[PlausibleConfig] = None
    fathom: typing.Optional[FathomConfig] = None
    clearbit: typing.Optional[ClearBitConfig] = None
    heap: typing.Optional[HeapConfig] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
