# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .js_file_config import JsFileConfig
from .js_remote_config import JsRemoteConfig


class JsConfig(UniversalBaseModel):
    remote: typing.Optional[typing.List[JsRemoteConfig]] = None
    files: typing.List[JsFileConfig]
    inline: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
