# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from .....core.pydantic_utilities import IS_PYDANTIC_V2
from .....core.serialization import FieldMetadata
from ...commons.types.subpackage_id import SubpackageId
from ...commons.types.with_description import WithDescription
from .api_definition_package import ApiDefinitionPackage


class ApiDefinitionSubpackage(ApiDefinitionPackage, WithDescription):
    subpackage_id: typing_extensions.Annotated[SubpackageId, FieldMetadata(alias="subpackageId")]
    name: str
    display_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="displayName")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
