# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....commons.types.url import Url
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from .with_node_id import WithNodeId


class LinkNode(WithNodeId):
    type: typing.Literal["link"] = "link"
    title: str
    icon: typing.Optional[str] = None
    url: Url

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
