# This file was auto-generated by Fern from our API Definition.

from ....v_1.commons.types.web_socket_message_id import (
    WebSocketMessageId as api_v_1_commons_types_web_socket_message_id_WebSocketMessageId,
)

WebSocketMessageId = api_v_1_commons_types_web_socket_message_id_WebSocketMessageId
