# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ......core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ......core.serialization import FieldMetadata
from ....commons.types.web_socket_message_id import WebSocketMessageId
from ....commons.types.web_socket_message_origin import WebSocketMessageOrigin
from ....commons.types.with_availability import WithAvailability
from ....commons.types.with_description import WithDescription
from .web_socket_message_body_shape import WebSocketMessageBodyShape


class WebSocketMessage(WithDescription, WithAvailability):
    type: WebSocketMessageId
    display_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="displayName")] = None
    origin: WebSocketMessageOrigin
    body: WebSocketMessageBodyShape

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...type.types.list_type import ListType  # noqa: E402, F401, I001
from ...type.types.map_type import MapType  # noqa: E402, F401, I001
from ...type.types.nullable_type import NullableType  # noqa: E402, F401, I001
from ...type.types.optional_type import OptionalType  # noqa: E402, F401, I001
from ...type.types.set_type import SetType  # noqa: E402, F401, I001

update_forward_refs(WebSocketMessage)
