# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from .....commons.types.page_id import PageId
from .....core.pydantic_utilities import IS_PYDANTIC_V2
from .navigation_node_metadata import NavigationNodeMetadata


class PageMetadata(NavigationNodeMetadata):
    id: PageId
    title: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
